# https://taskfile.dev

version: "3"

tasks:
  default:
    cmds:
      - air
  
  init:
    desc: Initialize the development environment
    cmds:
      - go run ./internal/store/db/migrate.go

  run:
    desc: Run the Go backend example application
    cmds:
      - go run ./cmd/main.go serve

  swagger:
    desc: Generate Swagger documentation
    cmds:
      - swag init -g ./cmd/main.go -o ./doc/swagger

  mcp-inspect:
    desc: Run MCP Inspector and stream logs
    cmds:
      - docker run -d --name mcp-inspector --rm --network host ghcr.io/modelcontextprotocol/inspector:latest
      - timeout 5s docker logs -f mcp-inspector

  mcp-inspect-stop:
    desc: Stop MCP Inspector
    cmds:
      - docker stop mcp-inspector
  
  migrate-add:*:
    desc: Create a new database migration
    vars:
      MIGRATE_NAME: '{{index .MATCH 0}}'
    env:
      GOOSE_DRIVER: sqlite3
      GOOSE_DBSTRING: ./data/data.db
      GOOSE_MIGRATION_DIR: ./migration
    cmds:
      - goose -s create {{.MIGRATE_NAME}} sql
  
  migrate-up:
    desc: Apply all up database migration
    cmds:
      - go run ./cmd/main.go migrate up migration

  migrate-down:
    desc: Apply all down database migration
    cmds:
      - go run ./cmd/main.go migrate down migration